spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
  data:
    cassandra:
      cluster-name: abc
      contact-points: localhost
      port: 9042
      keyspace-name: coe
      
      
        